=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Question.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Fred (Electronic Data Systems LTD) -->
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Fred (EDS LTD) -->
<!--
    $Header: /CVSRepository/clientoas/caseman/screens/caseman_wp/EnterVariableData/_Generic/Question.xsd,v 1.2 2006/03/01 15:40:59 conganer Exp $
    $Log: Question.xsd,v $
    Revision 1.2  2006/03/01 15:40:59  conganer
    WP Development Team OAS Migration

    Revision 1.9  2005/02/24 11:06:37  f_vdd
    *** empty log message ***

    Revision 1.8  2005/02/21 17:43:22  f_vdd
    *** empty log message ***

    Revision 1.7  2005/02/15 12:23:08  f_vdd
    *** empty log message ***

    Revision 1.6  2005/02/14 15:12:08  f_vdd
    provided for transformToModel, tranformToDisplay, validateOn, componentName and maxlength

    Revision 1.5  2005/01/31 16:11:37  f_vdd
    ongoing development

    Revision 1.4  2005/01/31 12:22:38  f_vdd
    *** empty log message ***

    Revision 1.3  2005/01/20 13:57:38  f_vdd
    *** empty log message ***

    Revision 1.2  2005/01/20 13:32:32  f_vdd
    *** empty log message ***

    Revision 1.1  2005/01/20 13:28:00  f_vdd
    *** empty log message ***

    Revision 1.1.2.3  2005/01/18 10:16:32  f_vdd
    Createing a meaningful CVS kkv keyword combination

    Revision 1.1.2.2  2005/01/18 10:15:19  f_vdd
    *** empty log message ***

  -->
<xs:schema targetNamespace="http://eds.com/questionxhtml" xmlns:ns1="http://eds.com/questionxhtml" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Question">
        <xs:annotation>
            <xs:documentation>A question represents a question field in a web application which is viewed as an HTML form widget.It extends the concept of the simple HTML form field with extensive javascript/XML object binding in use by the framework.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id">
                    <xs:annotation>
                        <xs:documentation>The Id of a Question defined in this XML is the name of this XML file (excl ext) and is used to compose Groups / Screens</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Label">
                    <xs:annotation>
                        <xs:documentation>The Label of a Question defined in this XML is the Label that will show on the HTML page(s) bareing this question.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="ObjectName">
                    <xs:annotation>
                        <xs:documentation>The ObjectName of a Question defined in this XML relates to the id of the browser HTML element and the name of the (framework configuration) JavaScript object</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Html">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Context" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="isVisible" minOccurs="0"/>
                            <xs:element name="Label"/>
                        </xs:sequence>
                        <xs:attribute name="ScreenId" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Javascript">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="XPath" type="xs:string"/>
                            <xs:element name="componentName"/>
                            <xs:element name="HintText" type="xs:string"/>
                            <xs:element name="initialise" type="xs:string" minOccurs="0"/>
                            <xs:element name="mandatoryOn" minOccurs="0"/>
                            <xs:element name="isMandatory" type="xs:string" minOccurs="0"/>
                            <xs:element name="validate" type="xs:string" minOccurs="0"/>
                            <xs:element name="validateOn" minOccurs="0"/>
                            <xs:element name="logic" minOccurs="0"/>
                            <xs:element name="logicOn" minOccurs="0"/>
                            <xs:element name="isEnabled" minOccurs="0"/>
                            <xs:element name="enableOn" minOccurs="0"/>
                            <xs:element name="postSetValue" type="xs:string" minOccurs="0"/>
                            <xs:element name="modelValue" type="xs:string" minOccurs="0"/>
                            <xs:element name="maxLength" minOccurs="0"/>
                            <xs:element name="transformToModel" minOccurs="0"/>
                            <xs:element name="transformToDisplay" minOccurs="0"/>
                            <xs:element name="miscCode" type="xs:string" minOccurs="0"/>
                            <xs:element name="readOnlyOn" type="xs:string" minOccurs="0"/>
                            <xs:element name="isReadOnly" type="xs:string" minOccurs="0"/>
                            <xs:element name="Context" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="HintText" type="xs:string" minOccurs="0"/>
                                        <xs:element name="initialise" type="xs:string" minOccurs="0"/>
                                        <xs:element name="mandatoryOn" minOccurs="0"/>
                                        <xs:element name="isMandatory" type="xs:string" minOccurs="0"/>
                                        <xs:element name="validate" type="xs:string" minOccurs="0"/>
                                        <xs:element name="validateOn" minOccurs="0"/>
                                        <xs:element name="logic" minOccurs="0"/>
                                        <xs:element name="logicOn" minOccurs="0"/>
                                        <xs:element name="isEnabled" minOccurs="0"/>
                                        <xs:element name="enableOn" minOccurs="0"/>
                                        <xs:element name="postSetValue" type="xs:string" minOccurs="0"/>
                                        <xs:element name="modelValue" type="xs:string" minOccurs="0"/>
                                        <xs:element name="maxLength" minOccurs="0"/>
                                        <xs:element name="transformToModel" minOccurs="0"/>
                                        <xs:element name="transformToDisplay" minOccurs="0"/>
                                        <xs:element name="miscCode" type="xs:string" minOccurs="0"/>
                                        <xs:element name="readOnlyOn" type="xs:string" minOccurs="0"/>
                                        <xs:element name="isReadOnly" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="ScreenId" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/806.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>806</Id>
	<Label>Maximum fine</Label>
	<ObjectName>MaximumFine</ObjectName>
	<Html>
	  <input id="DefaultCurrency806" type="text" size="1">
	  </input> <input id="MaximumFine" type="text" size="10"></input>
	</Html>
	<Javascript>
		<XPath>/ds/EnterVariableData/MaximumFine</XPath>
		<componentName>##label##</componentName>
		<HintText>Enter the maximum amount the debtor can be fined</HintText>
		<isMandatory>return true;</isMandatory>
		<mandatoryOn>MaximumFine.dataBinding</mandatoryOn>
		<validateOn>MaximumFine.dataBinding</validateOn>
		<validate>
			var val = Services.getValue(MaximumFine.dataBinding);
			var err = null;
			var maxVal = 999999.99;
			
			
			if('0.00' != val)
			{
				err = validateCurrencyValue(val, maxVal);
				if( null == err )
				{ 	
					var fVal = WPU.formatToTwoDP(val);
					Services.setValue(MaximumFine.dataBinding, fVal);
				}
			}
			return err;
		</validate>
		<miscCode>
			function DefaultCurrency806() {}
			DefaultCurrency806.dataBinding = "/ds/EnterVariableData/curr1";
			DefaultCurrency806.tabIndex = -1;
			DefaultCurrency806.maxLength = 1;
			DefaultCurrency806.isReadOnly = function(){return true;}
			DefaultCurrency806.isTemporary = function(){return true;}
			DefaultCurrency806.transformToDisplay = function(value){
				return WPS.__CaseManUtils().transformCurrencySymbolToDisplay(value,null,null); }
			DefaultCurrency806.transformToModel = function(value){
				return WPS.__CaseManUtils().transformCurrencySymbolToModel(value,null,null); }
		</miscCode>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/557.xml
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>557</Id>
	<Label>Amount of surety sum 1, if applicable</Label>
	<ObjectName>SuretySum1</ObjectName>
	<Html>	
		<input type="text" id="DefaultCurrency557" size="1"></input>
		<input type="text" id="SuretySum1"  size="11" maxlength="11"></input>
	</Html>			
	<Javascript>
		<XPath>/ds/EnterVariableData/Remand/suretySum1</XPath>
		<componentName>##label##</componentName>
		<isMandatory>return true;</isMandatory>
		<HintText>Enter the amount of the surety sum</HintText>
		<maxLength>11</maxLength>		
		<enableOn>BailConditionsSet.dataBinding</enableOn>
		<isEnabled>return( 'Y' == Services.getValue(BailConditionsSet.dataBinding));</isEnabled>
		<logicOn>BailConditionsSet.dataBinding</logicOn>
		<logic>
			if( 'Y' != Services.getValue(BailConditionsSet.dataBinding))
			{	Services.setValue(SuretySum1.dataBinding, "");
			}
		</logic>			
		<validateOn>SuretySum1.dataBinding</validateOn>
		<validate>
			var val = Services.getValue(SuretySum1.dataBinding);
			var err = validateCurrencyValue(val, 99999999.99);
			if( null == err )
			{	Services.setValue(SuretySum1.dataBinding, WPU.formatToTwoDP(val));
			}
			return err;
		</validate>
		<miscCode>
			function DefaultCurrency557() {}
			DefaultCurrency557.dataBinding = "/ds/EnterVariableData/curr1";
			DefaultCurrency557.tabIndex = -1;
			DefaultCurrency557.maxLength = 1;
			DefaultCurrency557.isReadOnly = function(){return true;}
			DefaultCurrency557.isTemporary = function(){return true;}
			DefaultCurrency557.transformToDisplay = function(value){
				return WPS.__CaseManUtils().transformCurrencySymbolToDisplay(value,null,null); }
			DefaultCurrency557.transformToModel = function(value){
				return WPS.__CaseManUtils().transformCurrencySymbolToModel(value,null,null); }
		</miscCode>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/34.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>34</Id>
	<Label>Date by which LQ to be filed</Label>
	<ObjectName>LqFiledByDate</ObjectName>
	<Html>
		<script type="text/javascript">WP_DatePickerRenderer.createInline("LqFiledByDate", false);</script>
	</Html>
	<Javascript>
		<XPath>/ds/EnterVariableData/LQFileByDate</XPath>
		<componentName>##label##</componentName>
		<HintText>Either select or enter return date for Listing Questionnaire, in the format DD-MON-YYYY</HintText>
		<isMandatory>return true;</isMandatory>			
		<mandatoryOn>LqFiledByDate.dataBinding</mandatoryOn>
		<initialise>			
			var expiryDate = Services.getValue("/ds/wp/MaintainObligations/Obligations/Obligation[ObligationType='3' and DeleteFlag='N']/ExpiryDate");
			Services.setValue(LqFiledByDate.dataBinding, expiryDate);			
		</initialise>
		<transformToModel>
		return transformDateToModel(value);
		</transformToModel>
		<transformToDisplay>
		if (value != null)
		{
			if (value.search(CaseManValidationHelper.YYYYMMDD_DATE_PATTERN) != -1)
			{
				return CaseManUtils.convertDateToDisplay(value);
			}
		}
		return value;
		</transformToDisplay>
		
		<Context ScreenId="CJR072">
			<HintText>Enter the date of listing questionnaire to be filed in the format DD-MMM-YYYY</HintText>
			<initialise>				
			</initialise>
			<validateOn>LqFiledByDate.dataBinding</validateOn>
			<validate>
				return isWorkingDayInFuture(Services.getValue(LqFiledByDate.dataBinding));
			</validate>
			<miscCode>LqFiledByDate.weekends = false;</miscCode>
			
			<enableOn>OrderDetails2.dataBinding</enableOn>
			<isEnabled>return('LQ' == Services.getValue(OrderDetails2.dataBinding));</isEnabled>
			<logicOn>OrderDetails2.dataBinding</logicOn>
			<logic>
				if('LQ' != Services.getValue(OrderDetails2.dataBinding))
				{	Services.setValue(LqFiledByDate.dataBinding, "");
				}
				else
				{	var expiryDate = Services.getValue("/ds/wp/MaintainObligations/Obligations/Obligation[./ObligationType = 8 ][last()]/ExpiryDate");
				    Services.setValue(LqFiledByDate.dataBinding, expiryDate);
				}
			</logic>
		
		</Context>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/430.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>430</Id>
	<Label>Enter details of 'Unless Order'</Label>
	<ObjectName>UODetails3</ObjectName>
	<Html>
		<input type="text" id="UODetails3"></input>
	</Html>
	
	<Javascript>
		<XPath>/ds/EnterVariableData/SmallTrack/uODetails3</XPath>
		<HintText>Enter details in full of 'Unless Order'</HintText>
		<isMandatory>return true;</isMandatory>
		<enableOn>UOOtherItems.dataBinding</enableOn>
		<isEnabled>return('Y' == Services.getValue(UOOtherItems.dataBinding));</isEnabled>
		<logicOn>UOOtherItems.dataBinding</logicOn>
		<logic>
			if('Y' != Services.getValue(UOOtherItems.dataBinding))
			{	Services.setValue(UODetails3.dataBinding, "");
			}
		</logic>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_oracle_reports/Questions/CM_WAREX_QUESTION_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	16/08/2006 - MGG - defect 4381 - setdefault to initialise.  After fixing this defect found validation to be incorrect
									changed the validatePastDate function
	03/10/2006 - MGG - defect 5305 - Ensure report only called once, for each date
-->
<!--Question xmlns="http://eds.com/questionxhtml" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd"-->
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>CM_WAREX_QUESTION_1</Id>
	<Label>Issue Date</Label>
	<ObjectName>IssueDate</ObjectName>
	<Html>
		<script type="text/javascript">
			DatePickerRenderer.createInline("IssueDate", false);
		</script>
	</Html>
	<Javascript>
		<XPath>/ds/var/page/OracleReportForm/IssueDate</XPath>
		<ReportVariableName>P_WAR_ISSUE_DATE</ReportVariableName>
		<ReportVariableValue>CaseManUtils.convertDateToDisplay(Services.getValue(IssueDate.dataBinding))</ReportVariableValue>
		<HintText>Enter an Issue Date in Past, eg 01-APR-2001</HintText>
		<isMandatory>return true;</isMandatory>
		<initialise>
			Services.setValue("/ds/var/app/OracleReportForm/CM_WAREX/ReportRun", "false");
			Services.setValue(IssueDate.dataBinding, getTodaysDate());
		</initialise>
		<logicOn>IssueDate.dataBinding</logicOn>
		<logic>
			var issueDate = Services.getValue(IssueDate.dataBinding);
			if(IssueDate.validate() == null)
			{
				Services.setValue("/ds/var/app/OracleReportForm/CM_WAREX/ReportRun", "false");	
				if (!CaseManUtils.isBlank(issueDate)) {
					checkExecutedWarrantsExist(issueDate);
				}
				else {
					Services.setValue(_executedWarrantsExistXPath, "true");
				}
			}
		</logic>
		<validateOn>IssueDate.dataBinding</validateOn>
		<validate>
			    var issueDate = Services.getValue(IssueDate.dataBinding);
			    var issueDateObj = CaseManUtils.isBlank(issueDate) ? null : CaseManUtils.createDate(issueDate);
			    var ec = null;
			    if(issueDateObj != null)
			    {
			      ec = validatePastDate(issueDateObj);     
			    }
			    return ec;		
		</validate>
		<miscCode>
			var _executedWarrantsExistXPath = "/ds/var/page/OracleReportForm/ExecutedWarrantsExist";

			Status_RunReportButton.validationList = ["IssueDate"];	
			
			function checkExecutedWarrantsExist(issueDate)
			{
				var params = new ServiceParams();
				params.addSimpleParameter("issueDate", CaseManUtils.convertDateToDisplay(issueDate));
				// var owningCourtCode = Services.getValue("/ds/var/page/tmp/OwningCourtCode");  // returns null
				var owningCourtCode = CaseManUtils.getUserParameter(CaseManFormParameters.COURTNUMBER_XPATH);
				params.addSimpleParameter("owningCourtCode", owningCourtCode);

				Services.callService("checkExecutedWarrantsExist", params, checkExecutedWarrantsExist, true);
			}
			checkExecutedWarrantsExist.onSuccess = function(dom)
			{
				if (dom != null) {
					var results = dom.selectSingleNode("/ExecutedWarrantsFound");
					if (results != null) {
						if (XML.getNodeTextContent(results) == 0) {
							Services.setValue(_executedWarrantsExistXPath, "false");
							alert("There are no Warrants to be printed.");
						}
						else {
							Services.setValue(_executedWarrantsExistXPath, "true");
						}
					}
					else {
						this.onError();
					}
				}
				else {
					this.onError();
				}
			}
			checkExecutedWarrantsExist.onError = function()
			{
				alert("Error querying database to check count of executed Warrants");
			}

			function validatePastDate(dateObj)
			{    
			  var todayDateObj = CaseManUtils.createDate(getTodaysDate());
			  // changed code to be efficient and correct.  date cannot be in the future
			  // but can be 'today'
			  // removed if(CaseManUtils.compareDates(todayDateObj, dateObj) == 0 || CaseManUtils.compareDates(todayDateObj, dateObj) == 1)
			  if(CaseManUtils.compareDates(todayDateObj, dateObj) == 1)
			  {
			    ec = ErrorCode.getErrorCode("CaseMan_dateCannotBeInTheFuture_Msg");
			    return faildedValidation (ec);
			  }
			  else
			  {
				return null;
			  }      
			  return null;   
			}			
			
			Status_RunReportButton.enableOn = [_executedWarrantsExistXPath,
											    "/ds/var/app/OracleReportForm/CM_WAREX/ReportRun"];
			Status_RunReportButton.isEnabled = function()
			{
				
			var returnValue = false;
			if (Services.getValue(_executedWarrantsExistXPath) == "true") {
				returnValue = true;
			}
			
			// defect 5305. Don't allow the report to run twice as prints empty report 2nd time.
			var reportRun = Services.getValue("/ds/var/app/OracleReportForm/CM_WAREX/ReportRun");
			if(reportRun != null){
				if(reportRun == "true"){
					returnValue = false;
				}
			}		
			
						
			return returnValue;
			}
		</miscCode>




	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/20.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>20</Id>
	<Label>Postcode</Label>
	<ObjectName>Postcode</ObjectName>
	<Html>
		<input id="Postcode" type="text" size="8"></input>
	</Html>
	
	<Context screenId="CJR082">
		<isVisible>true</isVisible>
		<Label>N40B Hearing postcode</Label>
	</Context>
	<Context screenId="CJR083">
		<isVisible>true</isVisible>
		<Label>N79A Hearing postcode</Label>
	</Context>
	
    <Context screenId="O_10_10"><isVisible>false</isVisible></Context>
    <Context screenId="O_10_12"><isVisible>false</isVisible></Context>

    
	<Javascript>
		<XPath>/ds/EnterVariableData/Hearing/Address/PostCode</XPath>
		<componentName>Hearing postcode</componentName>
		<HintText>Enter the hearing postcode</HintText>		
		<isReadOnly>return true;</isReadOnly>	
		<isMandatory>return false;</isMandatory>	
		<mandatoryOn>Postcode.dataBinding</mandatoryOn>
		<Notes>Auto populated from RefId 14</Notes>
		
		<Context ScreenId="O_11_1_2_3_4">	    	
			<enableOn>Postcode.dataBinding</enableOn>
			<isEnabled>if (null != WP &amp;&amp; null != WP.GetScreenProcess &amp;&amp; null != WP.GetScreenProcess()) { 
				var str = WPU.getValue( WPU.NODE_XPATHS['CaseEventId']);
				return(str == 690 || str == 692); }
			</isEnabled>
			<logicOn>AdLine1.dataBinding</logicOn>
			<logic>
				var str = WPU.getValue( WPU.NODE_XPATHS['CaseEventId']);
				if(str != 690 &amp;&amp; str != 692)
				{
					Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>
		<Context ScreenId="CJR093">
			<enableOn>WhoConsidApp2.dataBinding</enableOn>
			<isEnabled>return hearingFieldsEnabled();</isEnabled>
		</Context>
		<Context ScreenId="CJR072">
			<enableOn>OrderDetails2.dataBinding</enableOn>
			<isEnabled>return('HRG' == Services.getValue(OrderDetails2.dataBinding));</isEnabled>
			<logicOn>OrderDetails2.dataBinding</logicOn>
			<logic>
				if('HRG' != Services.getValue(OrderDetails2.dataBinding))
				{	Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>		
		<Context ScreenId="L_14_1">
			<initialise>
				WPU.loadBailiffRefData();
			</initialise>
		</Context>		
		<Context ScreenId="CJR178">
			<enableOn>WitnessTo.dataBinding</enableOn>
			<isEnabled>return( 'AC' == Services.getValue(WitnessTo.dataBinding));</isEnabled>
			<logicOn>WitnessTo.dataBinding</logicOn>
			<logic>
				if( 'AC' != Services.getValue(WitnessTo.dataBinding))
				{	Services.setValue(Postcode.dataBinding, "");
				}
			</logic>				
		</Context>		
		<Context ScreenId="CJR105">			
			<enableOn>NoticeOfFurtherHearing.dataBinding</enableOn>
			<isEnabled>return( 'Y' == Services.getValue(NoticeOfFurtherHearing.dataBinding));</isEnabled>
			<logicOn>NoticeOfFurtherHearing.dataBinding</logicOn>
			<logic>
				if( 'Y' != Services.getValue(NoticeOfFurtherHearing.dataBinding))
				{	Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>		
		<Context ScreenId="CJR060">
			<enableOn>TrialDateFixed.dataBinding</enableOn>
			<isEnabled>return('FIX' == Services.getValue(TrialDateFixed.dataBinding));</isEnabled>
			<logicOn>TrialDateFixed.dataBinding</logicOn>
			<logic>
				if('FIX' != Services.getValue(TrialDateFixed.dataBinding))
				{	Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>
		<Context ScreenId="CJR020">
			<enableOn>TrialDateFixed.dataBinding</enableOn>
			<isEnabled>return('FIX' == Services.getValue(TrialDateFixed.dataBinding));</isEnabled>
			<logicOn>TrialDateFixed.dataBinding</logicOn>
			<logic>
				if('FIX' != Services.getValue(TrialDateFixed.dataBinding))
				{	Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>
		<Context ScreenId="CJR061">			
			<enableOn>HearingListed.dataBinding</enableOn>
			<isEnabled>return('Y' == Services.getValue(HearingListed.dataBinding));</isEnabled>
			<logicOn>HearingListed.dataBinding</logicOn>
			<logic>
				if('Y' != Services.getValue(HearingListed.dataBinding));
				{	Services.setValue(AdLine2.dataBinding, "");
				}
			</logic>
		</Context>		
		<Context ScreenId="CJR046">	    	
			<enableOn>HearingListed.dataBinding</enableOn>
			<isEnabled>return ('Y' == Services.getValue(HearingListed.dataBinding));</isEnabled>
			<logicOn>HearingListed.dataBinding</logicOn>
			<logic>
				if('Y' != Services.getValue(HearingListed.dataBinding))
				{
					Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>		
		<Context ScreenId="CO23">
			<enableOn>DisStrAdj.dataBinding</enableOn>
			<isEnabled>return ('ADJ' == Services.getValue(DisStrAdj.dataBinding));</isEnabled>
			<logicOn>DisStrAdj.dataBinding</logicOn>
			<logic>
				if('ADJ' != Services.getValue(DisStrAdj.dataBinding))
				{
					Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>		
		<Context ScreenId="CO34">
			<enableOn>DisStrAdj.dataBinding</enableOn>
			<isEnabled>return ('ADJ' == Services.getValue(DisStrAdj.dataBinding));</isEnabled>
			<logicOn>DisStrAdj.dataBinding</logicOn>
			<logic>
				if('ADJ' != Services.getValue(DisStrAdj.dataBinding))
				{
					Services.setValue(Postcode.dataBinding, "");
				}
			</logic>
		</Context>
		  <Context ScreenId="O_2_6">
            <isEnabled>return true;</isEnabled>
        </Context>

		<Context ScreenId="O_3_1_2_5_1">
			<enableOn>VenueName.dataBinding</enableOn>
			<isEnabled>return( '' != Services.getValue(VenueName.dataBinding));</isEnabled>
			<logicOn>VenueName.dataBinding</logicOn>
			<logic>
				if( '' == Services.getValue(VenueName.dataBinding))
				{	Services.setValue(Postcode.dataBinding, "");
				}
			</logic>			
		</Context>	
	   <Context ScreenId="O_7_8">
            <isEnabled>return true;</isEnabled>
        </Context>		
        <Context ScreenId="O_10_7">
            <isEnabled>return true;</isEnabled>
        </Context>        
         <Context ScreenId="O_10_11">
            <isEnabled>return true;</isEnabled>
        </Context>

	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/580.xml
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>580</Id>
	<Label>Is there notice of a further hearing?</Label>
	<ObjectName>NoticeOfFurtherHearing</ObjectName>
	<Html>	
		<input type="checkbox" id="NoticeOfFurtherHearing"></input>
	</Html>			
	<Javascript>
		<XPath>/ds/EnterVariableData/Interlocutory/noticeOfFurtherHearing</XPath>
		<componentName>##label##</componentName>
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
		<HintText>Check box if there is notice of a further hearing?</HintText>	
		<enableOn>OrderToProduce.dataBinding</enableOn>
		<isEnabled>return( 'N16' == Services.getValue(OrderToProduce.dataBinding));</isEnabled>
		<logicOn>OrderToProduce.dataBinding</logicOn>
		<logic>
			if( 'N16' != Services.getValue(OrderToProduce.dataBinding))
			{	Services.setValue(NoticeOfFurtherHearing.dataBinding, "N");
			}
		</logic>			
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/199.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>199</Id>
	<Label>Documents relating to damage only</Label>
	<ObjectName>DamageDocs</ObjectName>
	<Html>	
		<input type="checkbox" id="DamageDocs"></input>
	</Html>
	<Javascript>
		<XPath>/ds/EnterVariableData/FastTrack/damageDocs</XPath>
		<HintText>Check box if documents relate to damage only</HintText>
		<!--isMandatory>return true;</isMandatory-->	
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
		<enableOn>IsLimitedDisclosure.dataBinding</enableOn>
		<isEnabled>return('Y' == Services.getValue(IsLimitedDisclosure.dataBinding))</isEnabled>
		<logicOn>IsLimitedDisclosure.dataBinding</logicOn>
		<logic>
			if('Y' != Services.getValue(IsLimitedDisclosure.dataBinding))
			{	Services.setValue(DamageDocs.dataBinding, "N");
			}
		</logic>
		<initialise>Services.setValue(DamageDocs.dataBinding, "N");</initialise>
	</Javascript>
</Question>
