=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Question.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Fred (Electronic Data Systems LTD) -->
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Fred (EDS LTD) -->
<!--
    $Header: /CVSRepository/clientoas/caseman/screens/caseman_wp/EnterVariableData/_Generic/Question.xsd,v 1.2 2006/03/01 15:40:59 conganer Exp $
    $Log: Question.xsd,v $
    Revision 1.2  2006/03/01 15:40:59  conganer
    WP Development Team OAS Migration

    Revision 1.9  2005/02/24 11:06:37  f_vdd
    *** empty log message ***

    Revision 1.8  2005/02/21 17:43:22  f_vdd
    *** empty log message ***

    Revision 1.7  2005/02/15 12:23:08  f_vdd
    *** empty log message ***

    Revision 1.6  2005/02/14 15:12:08  f_vdd
    provided for transformToModel, tranformToDisplay, validateOn, componentName and maxlength

    Revision 1.5  2005/01/31 16:11:37  f_vdd
    ongoing development

    Revision 1.4  2005/01/31 12:22:38  f_vdd
    *** empty log message ***

    Revision 1.3  2005/01/20 13:57:38  f_vdd
    *** empty log message ***

    Revision 1.2  2005/01/20 13:32:32  f_vdd
    *** empty log message ***

    Revision 1.1  2005/01/20 13:28:00  f_vdd
    *** empty log message ***

    Revision 1.1.2.3  2005/01/18 10:16:32  f_vdd
    Createing a meaningful CVS kkv keyword combination

    Revision 1.1.2.2  2005/01/18 10:15:19  f_vdd
    *** empty log message ***

  -->
<xs:schema targetNamespace="http://eds.com/questionxhtml" xmlns:ns1="http://eds.com/questionxhtml" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Question">
        <xs:annotation>
            <xs:documentation>A question represents a question field in a web application which is viewed as an HTML form widget.It extends the concept of the simple HTML form field with extensive javascript/XML object binding in use by the framework.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id">
                    <xs:annotation>
                        <xs:documentation>The Id of a Question defined in this XML is the name of this XML file (excl ext) and is used to compose Groups / Screens</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Label">
                    <xs:annotation>
                        <xs:documentation>The Label of a Question defined in this XML is the Label that will show on the HTML page(s) bareing this question.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="ObjectName">
                    <xs:annotation>
                        <xs:documentation>The ObjectName of a Question defined in this XML relates to the id of the browser HTML element and the name of the (framework configuration) JavaScript object</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Html">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Context" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="isVisible" minOccurs="0"/>
                            <xs:element name="Label"/>
                        </xs:sequence>
                        <xs:attribute name="ScreenId" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Javascript">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="XPath" type="xs:string"/>
                            <xs:element name="componentName"/>
                            <xs:element name="HintText" type="xs:string"/>
                            <xs:element name="initialise" type="xs:string" minOccurs="0"/>
                            <xs:element name="mandatoryOn" minOccurs="0"/>
                            <xs:element name="isMandatory" type="xs:string" minOccurs="0"/>
                            <xs:element name="validate" type="xs:string" minOccurs="0"/>
                            <xs:element name="validateOn" minOccurs="0"/>
                            <xs:element name="logic" minOccurs="0"/>
                            <xs:element name="logicOn" minOccurs="0"/>
                            <xs:element name="isEnabled" minOccurs="0"/>
                            <xs:element name="enableOn" minOccurs="0"/>
                            <xs:element name="postSetValue" type="xs:string" minOccurs="0"/>
                            <xs:element name="modelValue" type="xs:string" minOccurs="0"/>
                            <xs:element name="maxLength" minOccurs="0"/>
                            <xs:element name="transformToModel" minOccurs="0"/>
                            <xs:element name="transformToDisplay" minOccurs="0"/>
                            <xs:element name="miscCode" type="xs:string" minOccurs="0"/>
                            <xs:element name="readOnlyOn" type="xs:string" minOccurs="0"/>
                            <xs:element name="isReadOnly" type="xs:string" minOccurs="0"/>
                            <xs:element name="Context" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="HintText" type="xs:string" minOccurs="0"/>
                                        <xs:element name="initialise" type="xs:string" minOccurs="0"/>
                                        <xs:element name="mandatoryOn" minOccurs="0"/>
                                        <xs:element name="isMandatory" type="xs:string" minOccurs="0"/>
                                        <xs:element name="validate" type="xs:string" minOccurs="0"/>
                                        <xs:element name="validateOn" minOccurs="0"/>
                                        <xs:element name="logic" minOccurs="0"/>
                                        <xs:element name="logicOn" minOccurs="0"/>
                                        <xs:element name="isEnabled" minOccurs="0"/>
                                        <xs:element name="enableOn" minOccurs="0"/>
                                        <xs:element name="postSetValue" type="xs:string" minOccurs="0"/>
                                        <xs:element name="modelValue" type="xs:string" minOccurs="0"/>
                                        <xs:element name="maxLength" minOccurs="0"/>
                                        <xs:element name="transformToModel" minOccurs="0"/>
                                        <xs:element name="transformToDisplay" minOccurs="0"/>
                                        <xs:element name="miscCode" type="xs:string" minOccurs="0"/>
                                        <xs:element name="readOnlyOn" type="xs:string" minOccurs="0"/>
                                        <xs:element name="isReadOnly" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="ScreenId" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/488.xml
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>488</Id>
	<Label>Third party address 5</Label>
	<ObjectName>ThirdPartyAddress5</ObjectName>
	<Html>	
		<input type="text" id="ThirdPartyAddress5" size="50"></input>
	</Html>			
	<Javascript>
		<XPath>/ds/EnterVariableData/ThirdPartyDebt/ThirdParty/Address/Line[5]</XPath>
		<componentName>##label##</componentName>
		<isMandatory>return false;</isMandatory>
		<HintText>Fifth line of Third party/address</HintText>			
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/425.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>425</Id>
	<Label>Anything else be brought to the hearing?</Label>
	<ObjectName>BroughtToHearing</ObjectName>
	<Html>
		<input type="checkbox" id="BroughtToHearing"></input>
	</Html>
	
	<Javascript>
		<XPath>/ds/EnterVariableData/SmallTrack/broughtToHearing</XPath>
		<HintText>Check box if anything else is to be brought to the hearing</HintText>
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
		<enableOn>DirectionsTypeReqd.dataBinding, IsSpecialDirns.dataBinding, IsInspectDirns.dataBinding, UOInspectDirns.dataBinding, UODetails2.dataBinding</enableOn>
		<isEnabled>
			var val1 = Services.getValue(IsSpecialDirns.dataBinding);
			var val2 = Services.getValue(IsInspectDirns.dataBinding);
			var val3 = Services.getValue(UOInspectDirns.dataBinding);

			return('Y' == val1 || ( IsInspectDirns.isEnabled() &amp;&amp; 'Y' != val2 ) || (UOInspectDirns.isEnabled() &amp;&amp; 'Y' != val3 ) || UODetails2.isEnabled());
		</isEnabled>
		<logicOn>DirectionsTypeReqd.dataBinding, IsSpecialDirns.dataBinding, IsInspectDirns.dataBinding, UOInspectDirns.dataBinding, UODetails2.dataBinding</logicOn>
		<logic>
			var val1 = Services.getValue(IsSpecialDirns.dataBinding);
			var val2 = Services.getValue(IsInspectDirns.dataBinding);
			var val3 = Services.getValue(UOInspectDirns.dataBinding);
			if('Y' != val1 &amp;&amp; ( !IsInspectDirns.isEnabled() || 'Y' == val2 ) &amp;&amp; (!UOInspectDirns.isEnabled() || 'Y' == val3 )&amp;&amp; !UODetails2.isEnabled())
			{	Services.setValue(BroughtToHearing.dataBinding, "N");
			}
		</logic>
		<initialise>Services.setValue(BroughtToHearing.dataBinding, "N");</initialise>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/616.xml
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>616</Id>
	<Label>Is fund to be paid to child on majority?</Label>
	<ObjectName>PayOnMajority</ObjectName>

	<Html>	
		<input type="checkbox" id="PayOnMajority"></input>
	</Html>			
	<Javascript>
		<XPath>/ds/EnterVariableData/Settlement/payOnMajority</XPath>
		<componentName>##label##</componentName>
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
		<HintText>Check box if the fund is to be paid to child on majority</HintText>	
		<enableOn>ClaimFor.dataBinding, FatalAccidentSumTo.dataBinding</enableOn>
		<isEnabled>return('ACC' == Services.getValue(ClaimFor.dataBinding) &amp;&amp;
							'CLM' != Services.getValue(FatalAccidentSumTo.dataBinding));
		</isEnabled>
		<logicOn>ClaimFor.dataBinding, FatalAccidentSumTo.dataBinding</logicOn>
		<logic>
			if('ACC' != Services.getValue(ClaimFor.dataBinding) ||
							'CLM' == Services.getValue(FatalAccidentSumTo.dataBinding))
			{	Services.setValue(PayOnMajority.dataBinding, "N");
			}
		</logic>			
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/845.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>845</Id>
	<Label>CO status</Label>
	<ObjectName>COStatus</ObjectName>
	<Context ScreenId="CO19">
	</Context>
	
	<Html>
		<input id="COStatus" type="text"></input>
	</Html>
	<Javascript>
		<XPath>/ds/EnterVariableData/CODStatus</XPath>
		<componentName>##label##</componentName>
		<HintText></HintText>
		<isMandatory>return false;</isMandatory>
		<isReadOnly>return true;</isReadOnly>
		<mandatoryOn>COStatus.dataBinding</mandatoryOn>
		<initialise>
				var coStatus = WPU.getValue( WPU.NODE_XPATHS['COStatus'] );  			 			   	
			   	Services.setValue(COStatus.dataBinding,coStatus);
		</initialise>	
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/333.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>333</Id>
	<Label>Any additional daily payments.</Label>
	<ObjectName>HasAddDailyPayments</ObjectName>
	<Html>
		<input type="checkbox" id="HasAddDailyPayments"></input>
	</Html>
	
	<Context screenId="CJR052"><isVisible>false</isVisible></Context>
	<Context screenId="CJR053"><isVisible>false</isVisible></Context>
	<Context screenId="CJR055"><isVisible>false</isVisible></Context>
	
	<Javascript>
		<XPath>/ds/EnterVariableData/InterimCosts/PossessionOrder/hasAddDailyPayments</XPath>
		<componentName>##label##</componentName>
		<HintText>Check box if  there are any additional daily payments</HintText>
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/192.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>192</Id>
	<Label>Is limited disclosure ordered</Label>
	<ObjectName>IsLimitedDisclosure</ObjectName>
	<Html>	
		<input type="checkbox" id="IsLimitedDisclosure"></input>
	</Html>
	<Javascript>
		<XPath>/ds/EnterVariableData/FastTrack/isLimitedDisclosure</XPath>
		<HintText>Check box if limited disclosure is ordered</HintText>		
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
		<enableOn>IsDisclosureOrdered.dataBinding</enableOn>
		<isEnabled>return('Y' == Services.getValue(IsDisclosureOrdered.dataBinding));</isEnabled>
		<logicOn>IsDisclosureOrdered.dataBinding</logicOn>
		<logic>
			if('Y' != Services.getValue(IsDisclosureOrdered.dataBinding))
			{	Services.setValue(IsLimitedDisclosure.dataBinding, "N");
			}
		</logic>
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/452.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>452</Id>
	<Label>Other suspension details</Label>
	<ObjectName>OtherSuspDtls</ObjectName>
	<Html>			
		<input type="text" id="OtherSuspDtls"></input>		
	</Html>			
	<Javascript>
		<XPath>/ds/EnterVariableData/DisobedienceCommit/otherSuspDtls</XPath>
		<componentName>##label##</componentName>
		<isMandatory>return false;</isMandatory>
		<HintText>Enter any other suspension details ordered at N79A</HintText>			
	</Javascript>
</Question>

=== hmcts/poss/.business_context/SUPS-Caseman/app/client/src/main/webapp/screens/caseman_wp/EnterVariableData/_Generic/Questions/302.xml
<?xml version="1.0" encoding="UTF-8"?>
<Question xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eds.com/questionxhtml ..\Question.xsd">
	<Id>302</Id>
	<Label>Parties to try and agree nature of cost</Label>
	<ObjectName>PartiesAgreeCostNature</ObjectName>
	<Html>
		<input type="checkbox" id="PartiesAgreeCostNature"></input>
	</Html>
	
	<Javascript>
		<XPath>/ds/EnterVariableData/SmallTrack/partiesAgreeCostNature</XPath>
		<HintText>Check box if parties are to try and agree nature and cost of remedial work required</HintText>
		<modelValue>checked: "Y", unchecked: "N"</modelValue>
		<enableOn>BringOrigDocs.dataBinding, DirectionsTypeReqd.dataBinding, 
				IsWorkMaterialsFiledList.dataBinding, IsPartiesToAgreeRepairs.dataBinding
		</enableOn>
		<isEnabled>
			var val2 = Services.getValue(DirectionsTypeReqd.dataBinding);
			if(IsWorkMaterialsFiledList.isEnabled() &amp;&amp; 'SD' != val2 &amp;&amp; !SketchPlansPhotosReqd.isEnabled() &amp;&amp; 'RDDT' != val2 ){ return true; }
			else if( 'SPEC'  == val2 || 'HW' == val2 || IsPartiesToAgreeRepairs.isEnabled() ){ return false; }
			
		<!--	return((val2 != "RDDT") &amp;&amp; !SketchPlansPhotosReqd.isEnabled()); -->
		</isEnabled>
		<logicOn>BringOrigDocs.dataBinding, DirectionsTypeReqd.dataBinding</logicOn>
		<logic>
			var val2 = Services.getValue(DirectionsTypeReqd.dataBinding);
			if(!IsWorkMaterialsFiledList.isEnabled() || 'SD' == val2 || SketchPlansPhotosReqd.isEnabled() || 'RDDT' == val2 )
			{	Services.setValue(PartiesAgreeCostNature.dataBinding, "N");
			}
	
		</logic>		
	</Javascript>
</Question>
